name: Hello World!

on:
 push:
  branch: master

jobs: 
 hello_world_job: 
  runs-on: ubuntu-20.04
  steps: 
   - name: Say Hello
     run: |
      echo "Hello World!"
   - name: Show the date
     run: date   

   - name: List files permissions 
     run: ls -l
   - name: Check the present directory
     run: pwd     
       


